# Generated by Django 5.2.2 on 2025-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(default='Dental Clinic', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='Dentist', max_length=100),
        ),
    ]
